INSERT INTO clients VALUES (default, 'Eduardo', 'Rodriguez', 'edu34@gmail.com', 5513733506,	true);
INSERT INTO clients VALUES (default, 'Andrea', 'Velazquez', 'andrea01@gmail.com', 5513754712, true);
INSERT INTO clients VALUES (default, 'Paulina', 'Hernandez', 'pau_21@gmail.com', 5513733804, true);
INSERT INTO clients VALUES (default, 'Andres', 'Vargas', 'andreu@gmail.com', 5513875439, false);
INSERT INTO clients VALUES (default, 'Gustavo', 'Salinas', 'gus_salinas@gmail.com', 5514785263, true);
INSERT INTO clients VALUES (default, 'Juan', 'Torres', 'juantorres90@gmail.com', 5513874593, false);
INSERT INTO clients VALUES (default, 'Veronica', 'Lopez', 'veronica_lo@gmail.com',	5513737541, true);
INSERT INTO clients VALUES (default, 'Diana', 'Licea',	'dianalicea@gmail.com',	5513733253, true);
INSERT INTO clients VALUES (default, 'Diego', 'Martinez', 'diego.mar@gmail.com', 5513452189, true);

INSERT INTO memberships VALUES (default, 'Iron', '150',	1, true);
INSERT INTO memberships VALUES (default, 'Silver', '170', 3, true);
INSERT INTO memberships VALUES (default, 'Gold', '200',	6, true);
INSERT INTO memberships VALUES (default, 'Platinum', '250',	12, true);
INSERT INTO memberships VALUES (default, 'basic', '200', 2, false);
INSERT INTO memberships VALUES (default, 'pro',	'30', 12, false);

insert into payments values(default, 3, 1, 220, '2021-01-02');
insert into payments values(default, 1, 2, 110, '2020-04-05');
insert into payments values(default, 2, 3, 195, '2020-03-02');
insert into payments values(default, 4, 4, 270, '2020-07-21');
insert into payments values(default, 4, 5, 270, '2020-05-15');

INSERT INTO classes VALUES (default, 'Body Jam', 'Hector Silva', 'hector20@gmail.com',	true);
INSERT INTO classes VALUES (default, 'TRX', 'Ana Licea', 'ana.licea@gmail.com', true);
INSERT INTO classes VALUES (default, 'CrossFit', 'Julio Lopez', 'juliolopez@gmail.com', true);
INSERT INTO classes VALUES (default, 'Power Jump', 'Karla Martinez', 'karla94@gmail.com', true);
INSERT INTO classes VALUES (default, 'TaeBo',	'Octavio Herrera', 'octavioherrera@gmail.com', true);
INSERT INTO classes VALUES (default, 'Zumba', 'Maria Pereira', 'maria.pereira@gmail.com',	true);
INSERT INTO classes VALUES (default, 'Spinning', 'Fernanda Ochoa',	'fernanda.ochoa@gmail.com', true);

INSERT INTO "mondaySchedule" VALUES(default, 1, '07:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 1, '08:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 1, '10:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 1, '17:00:00', false);
INSERT INTO "mondaySchedule" VALUES(default, 1, '18:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 1, '20:00:00', false);
INSERT INTO "mondaySchedule" VALUES(default, 2, '07:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 2, '08:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 2, '10:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 2, '17:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 2, '18:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 2, '20:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 3, '07:00:00', false);
INSERT INTO "mondaySchedule" VALUES(default, 3, '08:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 3, '10:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 3, '17:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 3, '18:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 3, '20:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 4, '07:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 4, '08:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 4, '10:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 4, '17:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 4, '18:00:00', false);
INSERT INTO "mondaySchedule" VALUES(default, 4, '20:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 5, '07:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 5, '08:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 5, '10:00:00', false);
INSERT INTO "mondaySchedule" VALUES(default, 5, '17:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 5, '18:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 5, '20:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 6, '07:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 6, '08:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 6, '10:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 6, '17:00:00', false);
INSERT INTO "mondaySchedule" VALUES(default, 6, '18:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 6, '20:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 7, '07:00:00', false);
INSERT INTO "mondaySchedule" VALUES(default, 7, '08:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 7, '10:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 7, '17:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 7, '18:00:00', true);
INSERT INTO "mondaySchedule" VALUES(default, 7, '20:00:00', true);

INSERT INTO "tuesdaySchedule" VALUES(default, 1, '07:00:00', false);
INSERT INTO "tuesdaySchedule" VALUES(default, 1, '08:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 1, '10:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 1, '17:00:00', false);
INSERT INTO "tuesdaySchedule" VALUES(default, 1, '18:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 1, '20:00:00', false);
INSERT INTO "tuesdaySchedule" VALUES(default, 2, '07:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 2, '08:00:00', false);
INSERT INTO "tuesdaySchedule" VALUES(default, 2, '10:00:00', false);
INSERT INTO "tuesdaySchedule" VALUES(default, 2, '17:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 2, '18:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 2, '20:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 3, '07:00:00', false);
INSERT INTO "tuesdaySchedule" VALUES(default, 3, '08:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 3, '10:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 3, '17:00:00', false);
INSERT INTO "tuesdaySchedule" VALUES(default, 3, '18:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 3, '20:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 4, '07:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 4, '08:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 4, '10:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 4, '17:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 4, '18:00:00', false);
INSERT INTO "tuesdaySchedule" VALUES(default, 4, '20:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 5, '07:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 5, '08:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 5, '10:00:00', false);
INSERT INTO "tuesdaySchedule" VALUES(default, 5, '17:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 5, '18:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 5, '20:00:00', false);
INSERT INTO "tuesdaySchedule" VALUES(default, 6, '07:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 6, '08:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 6, '10:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 6, '17:00:00', false);
INSERT INTO "tuesdaySchedule" VALUES(default, 6, '18:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 6, '20:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 7, '07:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 7, '08:00:00', false);
INSERT INTO "tuesdaySchedule" VALUES(default, 7, '10:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 7, '17:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 7, '18:00:00', true);
INSERT INTO "tuesdaySchedule" VALUES(default, 7, '20:00:00', false);

INSERT INTO "wednesdaySchedule" VALUES(default, 1, '07:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 1, '08:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 1, '10:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 1, '17:00:00', false);
INSERT INTO "wednesdaySchedule" VALUES(default, 1, '18:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 1, '20:00:00', false);
INSERT INTO "wednesdaySchedule" VALUES(default, 2, '07:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 2, '08:00:00', false);
INSERT INTO "wednesdaySchedule" VALUES(default, 2, '10:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 2, '17:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 2, '18:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 2, '20:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 3, '07:00:00', false);
INSERT INTO "wednesdaySchedule" VALUES(default, 3, '08:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 3, '10:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 3, '17:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 3, '18:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 3, '20:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 4, '07:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 4, '08:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 4, '10:00:00', false);
INSERT INTO "wednesdaySchedule" VALUES(default, 4, '17:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 4, '18:00:00', false);
INSERT INTO "wednesdaySchedule" VALUES(default, 4, '20:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 5, '07:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 5, '08:00:00', false);
INSERT INTO "wednesdaySchedule" VALUES(default, 5, '10:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 5, '17:00:00', false);
INSERT INTO "wednesdaySchedule" VALUES(default, 5, '18:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 5, '20:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 6, '07:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 6, '08:00:00', false);
INSERT INTO "wednesdaySchedule" VALUES(default, 6, '10:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 6, '17:00:00', false);
INSERT INTO "wednesdaySchedule" VALUES(default, 6, '18:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 6, '20:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 7, '07:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 7, '08:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 7, '10:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 7, '17:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 7, '18:00:00', true);
INSERT INTO "wednesdaySchedule" VALUES(default, 7, '20:00:00', true);

INSERT INTO "thursdaySchedule" VALUES(default, 1, '07:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 1, '08:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 1, '10:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 1, '17:00:00', false);
INSERT INTO "thursdaySchedule" VALUES(default, 1, '18:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 1, '20:00:00', false);
INSERT INTO "thursdaySchedule" VALUES(default, 2, '07:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 2, '08:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 2, '10:00:00', false);
INSERT INTO "thursdaySchedule" VALUES(default, 2, '17:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 2, '18:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 2, '20:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 3, '07:00:00', false);
INSERT INTO "thursdaySchedule" VALUES(default, 3, '08:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 3, '10:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 3, '17:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 3, '18:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 3, '20:00:00', false);
INSERT INTO "thursdaySchedule" VALUES(default, 4, '07:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 4, '08:00:00', false);
INSERT INTO "thursdaySchedule" VALUES(default, 4, '10:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 4, '17:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 4, '18:00:00', false);
INSERT INTO "thursdaySchedule" VALUES(default, 4, '20:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 5, '07:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 5, '08:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 5, '10:00:00', false);
INSERT INTO "thursdaySchedule" VALUES(default, 5, '17:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 5, '18:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 5, '20:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 6, '07:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 6, '08:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 6, '10:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 6, '17:00:00', false);
INSERT INTO "thursdaySchedule" VALUES(default, 6, '18:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 6, '20:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 7, '07:00:00', false);
INSERT INTO "thursdaySchedule" VALUES(default, 7, '08:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 7, '10:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 7, '17:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 7, '18:00:00', true);
INSERT INTO "thursdaySchedule" VALUES(default, 7, '20:00:00', true);

INSERT INTO "fridaySchedule" VALUES(default, 1, '07:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 1, '08:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 1, '10:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 1, '17:00:00', false);
INSERT INTO "fridaySchedule" VALUES(default, 1, '18:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 1, '20:00:00', false);
INSERT INTO "fridaySchedule" VALUES(default, 2, '07:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 2, '08:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 2, '10:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 2, '17:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 2, '18:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 2, '20:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 3, '07:00:00', false);
INSERT INTO "fridaySchedule" VALUES(default, 3, '08:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 3, '10:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 3, '17:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 3, '18:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 3, '20:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 4, '07:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 4, '08:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 4, '10:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 4, '17:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 4, '18:00:00', false);
INSERT INTO "fridaySchedule" VALUES(default, 4, '20:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 5, '07:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 5, '08:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 5, '10:00:00', false);
INSERT INTO "fridaySchedule" VALUES(default, 5, '17:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 5, '18:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 5, '20:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 6, '07:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 6, '08:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 6, '10:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 6, '17:00:00', false);
INSERT INTO "fridaySchedule" VALUES(default, 6, '18:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 6, '20:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 7, '07:00:00', false);
INSERT INTO "fridaySchedule" VALUES(default, 7, '08:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 7, '10:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 7, '17:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 7, '18:00:00', true);
INSERT INTO "fridaySchedule" VALUES(default, 7, '20:00:00', true);

INSERT INTO "saturdaySchedule" VALUES(default, 1, '07:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 1, '08:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 1, '10:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 1, '17:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 1, '18:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 1, '20:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 2, '07:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 2, '08:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 2, '10:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 2, '17:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 2, '18:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 2, '20:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 3, '07:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 3, '08:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 3, '10:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 3, '17:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 3, '18:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 3, '20:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 4, '07:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 4, '08:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 4, '10:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 4, '17:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 4, '18:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 4, '20:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 5, '07:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 5, '08:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 5, '10:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 5, '17:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 5, '18:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 5, '20:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 6, '07:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 6, '08:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 6, '10:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 6, '17:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 6, '18:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 6, '20:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 7, '07:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 7, '08:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 7, '10:00:00', true);
INSERT INTO "saturdaySchedule" VALUES(default, 7, '17:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 7, '18:00:00', false);
INSERT INTO "saturdaySchedule" VALUES(default, 7, '20:00:00', false);